### ISSUE TITLE
Remove (responsive) slider if all elements fit on a page

### ISSUE THREAD

**Issue by MaluNoPeleke** [electerious/basicSlider#4]
For an integration in a CMS where I don't know how many items will be added to a gallery with the slider it would be great if no next/prev buttons are visible if all elements can be shown already.

**Comment by electerious** [comment]
This feature isn't in the scope of basicSlider, but you can calculate if basicLightbox should show arrows or not and then pass the result to basicLightbox.

Something like:

```js
const instance = basicSlider.create(document.querySelector('#slider'), [
	'<p>Slide 1 with HTML</p>',
	'<p>Slide 2 with HTML</p>',
	'<p>Slide 3 with HTML</p>'
], {
	index: 1,
	arrows: calculateIfAllElementsCanBeShown()
})
```

I hope this helps!
